// packages/react/src/mira-mde.tsx
import type { Extension } from "@codemirror/state";
import {
  createBaseCodeMirrorExtensions,
  createSlashCommandExtensions,
} from "@mira-mde/codemirror";
import {
  createMarkdownAuthoringExtensions,
  createMarkdownCodeMirrorExtensions,
} from "@mira-mde/codemirror-markdown";
import { createRichEditorExtensions } from "@mira-mde/codemirror-rich";
import { createTableExtensions } from "@mira-mde/codemirror-tables";
import {
  createImageDropPasteExtension,
  createMiraEditorController,
  openImageFilePicker,
  type MiraEditorController,
} from "@mira-mde/core";
import {
  createMiraCommandKeymap,
  executeMiraCommand,
  isMiraCommandEnabled,
  mountMiraExtensionStyles,
  resolveMiraExtensions,
  type MiraCommand,
  type MiraExtensionRuntimeContext,
  type MiraMode,
  type MiraTemplateSelection,
  type MiraTheme,
  type MiraThemeConfig,
} from "@mira-mde/extensions";
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  type RefObject,
} from "react";
import { useLatestRef, cx } from "./hooks";
import { MarkdownPreviewHost } from "./preview-host";
import type { MiraMdeHandle, MiraMdeProps } from "./types";

const defaultMode: MiraMode = "live-preview";

export const MiraMde = forwardRef<MiraMdeHandle, MiraMdeProps>(function MiraMde(
  {
    assetResolver,
    authoring,
    className,
    defaultMode: defaultModeProp = defaultMode,
    defaultReadonly = false,
    defaultValue = "",
    extensions = [],
    fileAdapter,
    imageConfig,
    frontmatterOpen = true,
    frontmatterConfig,
    headingIds = false,
    headingIdPrefix = "",
    htmlPolicy = "trusted",
    emoji = false,
    outline = false,
    outlineVariant = "floating",
    blockControls = false,
    indentGuides = true,
    indentWithTabs = true,
    indentWidth = 4,
    lineWrapping = true,
    linkResolver,
    mode: modeProp,
    onChange,
    onFrontmatterChange,
    onModeChange,
    onReadonlyChange,
    placeholder = "Start writing Markdown...",
    readonly: readonlyProp,
    sourcePath,
    spellcheck = true,
    theme = "obsidian",
    themeConfig,
    toolbar = true,
    value: valueProp,
  },
  ref,
) {
  const editorHostRef = useRef<HTMLDivElement | null>(null);
  const previewPaneRef = useRef<HTMLElement | null>(null);
  const rootRef = useRef<HTMLDivElement | null>(null);
  const controllerRef = useRef<MiraEditorController | null>(null);
  const cleanupExtensionMountsRef = useRef<Array<() => void>>([]);
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
  const [uncontrolledMode, setUncontrolledMode] = useState(defaultModeProp);
  const [uncontrolledReadonly, setUncontrolledReadonly] =
    useState(defaultReadonly);
  const value = valueProp ?? uncontrolledValue;
  const mode = modeProp ?? uncontrolledMode;
  const readonly = readonlyProp ?? uncontrolledReadonly;
  const valueRef = useLatestRef(value);
  const modeRef = useLatestRef(mode);
  const readonlyRef = useLatestRef(readonly);
  const onChangeRef = useLatestRef(onChange);
  const onModeChangeRef = useLatestRef(onModeChange);
  const onReadonlyChangeRef = useLatestRef(onReadonlyChange);
  const onFrontmatterChangeRef = useLatestRef(onFrontmatterChange);

  const resolvedExtensions = useMemo(
    () =>
      resolveMiraExtensions(extensions, {
        mode,
        readonly,
        sourcePath,
      }),
    [extensions, mode, readonly, sourcePath],
  );

  const commitValue = useCallback(
    (nextValue: string) => {
      if (valueProp === undefined) {
        setUncontrolledValue(nextValue);
      }
      onChangeRef.current?.(nextValue);
    },
    [onChangeRef, valueProp],
  );

  const setMode = useCallback(
    (nextMode: MiraMode) => {
      if (modeProp === undefined) {
        setUncontrolledMode(nextMode);
      }
      onModeChangeRef.current?.(nextMode);
    },
    [modeProp, onModeChangeRef],
  );

  const setReadonly = useCallback(
    (nextReadonly: boolean) => {
      if (readonlyProp === undefined) {
        setUncontrolledReadonly(nextReadonly);
      }
      onReadonlyChangeRef.current?.(nextReadonly);
    },
    [onReadonlyChangeRef, readonlyProp],
  );

  const handleInsertMarkdown = useCallback(
    (markdown: string, selection?: MiraTemplateSelection) => {
      const controller = controllerRef.current;
      controller?.replaceSelection(markdown, selection);
      controller?.focus();
    },
    [],
  );

  const handleInsertImage = useCallback(() => {
    const controller = controllerRef.current;
    if (controller) {
      openImageFilePicker(controller.view, imageConfig);
    }
  }, [imageConfig]);

  const createExtensionRuntimeContext = useCallback(
    (
      activeController: MiraEditorController | null = controllerRef.current,
      view: unknown = activeController?.view,
    ): MiraExtensionRuntimeContext => ({
      view,
      mode: modeRef.current,
      readonly: readonlyRef.current,
      sourcePath,
      focus: () => activeController?.focus(),
      getValue: () => activeController?.getValue() ?? valueRef.current,
      insertImage: handleInsertImage,
      insertMarkdown: handleInsertMarkdown,
      setValue(nextValue) {
        if (valueProp === undefined) {
          setUncontrolledValue(nextValue);
        }
        activeController?.setValue(nextValue);
      },
    }),
    [
      handleInsertImage,
      handleInsertMarkdown,
      modeRef,
      readonlyRef,
      sourcePath,
      valueProp,
      valueRef,
    ],
  );

  const buildCodeMirrorExtensions = useCallback((): Extension[] => {
    const resolved = resolveMiraExtensions(extensions, {
      mode: modeRef.current,
      readonly: readonlyRef.current,
      sourcePath,
    });

    return [
      createBaseCodeMirrorExtensions({
        indentWithTabs,
        indentWidth,
        lineWrapping,
        placeholder,
        readonly: readonlyRef.current,
        spellcheck,
      }),
      createSlashCommandExtensions({
        commands: resolved.slashCommands,
      }),
      createMiraCommandKeymap(resolved.commands, (view) =>
        createExtensionRuntimeContext(controllerRef.current, view),
      ),
      createMarkdownCodeMirrorExtensions({
        codeLanguages: resolved.codeLanguages,
        sourceMode: modeRef.current === "source",
      }),
      createTableExtensions(),
      createImageDropPasteExtension(imageConfig),
      createMarkdownAuthoringExtensions({
        config: authoring,
        fileAdapter,
        sourcePath,
      }),
      createRichEditorExtensions({
        assetResolver,
        blockActions: resolved.blockActions,
        blockControls:
          blockControls &&
          modeRef.current !== "preview" &&
          !readonlyRef.current,
        extensions,
        fileAdapter,
        frontmatterConfig,
        frontmatterOpen,
        indentGuides,
        linkResolver,
        livePreview: modeRef.current === "live-preview",
        onChange(replacement, from, to, nextValue) {
          const controller = controllerRef.current;
          if (controller) {
            controller.view.dispatch({
              changes: { from, insert: replacement, to },
            });
          } else {
            commitValue(nextValue);
          }
        },
        onFrontmatterChange: (...args) =>
          onFrontmatterChangeRef.current?.(...args),
        sourcePath,
      } as Parameters<typeof createRichEditorExtensions>[0] & {
        frontmatterConfig?: unknown;
        fileAdapter?: unknown;
      }),
      resolved.codeMirror,
    ].flat();
  }, [
    assetResolver,
    authoring,
    blockControls,
    commitValue,
    createExtensionRuntimeContext,
    extensions,
    fileAdapter,
    frontmatterOpen,
    frontmatterConfig,
    indentGuides,
    indentWithTabs,
    indentWidth,
    imageConfig,
    lineWrapping,
    linkResolver,
    modeRef,
    onFrontmatterChangeRef,
    placeholder,
    readonlyRef,
    sourcePath,
    spellcheck,
  ]);

  const runExtensionMounts = useCallback(
    (activeController: MiraEditorController) => {
      for (const cleanup of cleanupExtensionMountsRef.current) {
        cleanup();
      }
      cleanupExtensionMountsRef.current = [];

      for (const mountExtension of resolvedExtensions.onMount) {
        const cleanup = mountExtension(
          createExtensionRuntimeContext(
            activeController,
            activeController.view,
          ),
        );
        if (typeof cleanup === "function") {
          cleanupExtensionMountsRef.current.push(cleanup);
        }
      }
    },
    [createExtensionRuntimeContext, resolvedExtensions.onMount],
  );

  const findCommand = useCallback(
    (commandId: string): MiraCommand | undefined => {
      for (
        let index = resolvedExtensions.commands.length - 1;
        index >= 0;
        index -= 1
      ) {
        const command = resolvedExtensions.commands[index];
        if (command?.id === commandId) {
          return command;
        }
      }
      return undefined;
    },
    [resolvedExtensions.commands],
  );

  const isCommandEnabled = useCallback(
    (commandId: string): boolean => {
      const command = findCommand(commandId);
      return Boolean(
        command &&
        isMiraCommandEnabled(command, createExtensionRuntimeContext()),
      );
    },
    [createExtensionRuntimeContext, findCommand],
  );

  const executeCommand = useCallback(
    (commandId: string): boolean =>
      executeMiraCommand(
        resolvedExtensions.commands,
        commandId,
        createExtensionRuntimeContext(),
      ),
    [createExtensionRuntimeContext, resolvedExtensions.commands],
  );

  useEffect(() => {
    if (!editorHostRef.current) {
      return;
    }

    const activeController = createMiraEditorController({
      codeMirrorExtensions: buildCodeMirrorExtensions(),
      onChange(nextValue) {
        commitValue(nextValue);
      },
      value,
    });

    activeController.mount(editorHostRef.current);
    controllerRef.current = activeController;
    runExtensionMounts(activeController);

    return () => {
      for (const cleanup of cleanupExtensionMountsRef.current) {
        cleanup();
      }
      cleanupExtensionMountsRef.current = [];
      activeController.destroy();
      controllerRef.current = null;
    };
  }, []);

  useEffect(() => {
    const controller = controllerRef.current;
    if (controller && value !== controller.getValue()) {
      controller.setValue(value);
    }
  }, [value]);

  useEffect(
    () => mountMiraExtensionStyles(resolvedExtensions.styles),
    [resolvedExtensions.styles],
  );

  useEffect(() => {
    const controller = controllerRef.current;
    if (!controller) {
      return;
    }
    controller.update({
      codeMirrorExtensions: buildCodeMirrorExtensions(),
    });
    runExtensionMounts(controller);
  }, [buildCodeMirrorExtensions, runExtensionMounts]);

  const handlePreviewChange = useCallback(
    (replacement: string, from: number, to: number) => {
      const currentValue = valueRef.current;
      const nextValue = `${currentValue.slice(0, from)}${replacement}${currentValue.slice(to)}`;
      commitValue(nextValue);
    },
    [commitValue, valueRef],
  );

  useImperativeHandle(
    ref,
    () => ({
      executeCommand,
      focus() {
        controllerRef.current?.focus();
      },
      getMarkdown() {
        return controllerRef.current?.getValue() ?? valueRef.current;
      },
      getCommands() {
        return resolvedExtensions.commands;
      },
      getMode() {
        return modeRef.current;
      },
      getSelection() {
        return controllerRef.current?.getSelection() ?? null;
      },
      insertMarkdown: handleInsertMarkdown,
      insertImage: handleInsertImage,
      isCommandEnabled,
      setMarkdown(markdown) {
        if (valueProp === undefined) {
          setUncontrolledValue(markdown);
        }
        controllerRef.current?.setValue(markdown);
      },
      setMode,
      setReadonly,
      setSelection(selection) {
        controllerRef.current?.setSelection(selection);
      },
    }),
    [
      handleInsertImage,
      handleInsertMarkdown,
      executeCommand,
      isCommandEnabled,
      modeRef,
      resolvedExtensions.commands,
      setMode,
      setReadonly,
      valueProp,
      valueRef,
    ],
  );

  const showEditor = mode !== "preview";
  const showPreview = mode === "preview" || mode === "split";
  const inheritedTheme = useInheritedTheme(theme, themeConfig, rootRef);
  const themeClass = themeClassName(
    theme === "inherit" ? inheritedTheme : theme,
  );

  useEffect(() => {
    const controller = controllerRef.current;
    const previewPane = previewPaneRef.current;
    if (mode !== "split" || !controller || !previewPane) {
      return;
    }

    return syncSplitScroll(controller.view.scrollDOM, previewPane);
  }, [mode, showPreview]);

  return (
    <div
      className={cx("mira-mde", themeClass, className)}
      data-mode={mode}
      data-readonly={readonly}
      ref={rootRef}
    >
      {toolbar ? (
        <div className="mira-mde__toolbar" aria-label="Markdown editor toolbar">
          <div className="mira-toggle-group" aria-label="Editor mode">
            {(["source", "live-preview", "preview", "split"] as MiraMode[]).map(
              (modeOption) => (
                <button
                  className="mira-toggle-group__item"
                  data-state={mode === modeOption ? "on" : "off"}
                  key={modeOption}
                  onClick={() => setMode(modeOption)}
                  type="button"
                >
                  {modeOption === "live-preview" ? "Live" : modeOption}
                </button>
              ),
            )}
          </div>
          <div className="mira-separator--vertical mira-mde__toolbar-separator" />
          <div className="mira-mde__actions">
            <button
              className="mira-ui-button mira-ui-button--ghost mira-ui-button--sm"
              onClick={() => handleInsertMarkdown("**strong**")}
              type="button"
            >
              B
            </button>
            <button
              className="mira-ui-button mira-ui-button--ghost mira-ui-button--sm"
              onClick={() => handleInsertMarkdown("_emphasis_")}
              type="button"
            >
              I
            </button>
            <button
              className="mira-ui-button mira-ui-button--ghost mira-ui-button--sm"
              onClick={() =>
                handleInsertMarkdown("[label](https://example.com)")
              }
              type="button"
            >
              Link
            </button>
            <button
              className="mira-ui-button mira-ui-button--ghost mira-ui-button--sm"
              onClick={handleInsertImage}
              type="button"
            >
              Image
            </button>
          </div>
        </div>
      ) : null}

      <div className="mira-mde__body">
        <section
          aria-hidden={showEditor ? "false" : "true"}
          className={cx(
            "mira-mde__pane mira-mde__pane--editor markdown-editor-surface",
            mode === "source"
              ? "markdown-view__editor--source markdown-source-mode"
              : "markdown-view__editor--live-preview markdown-live-preview-mode",
          )}
          data-visible={showEditor}
        >
          <div className="mira-mde__editor-host" ref={editorHostRef} />
        </section>

        {showPreview ? (
          <section
            className={cx(
              "mira-mde__pane mira-mde__pane--preview",
              outline && outlineVariant === "floating"
                ? "mira-mde__pane--outline-floating"
                : undefined,
            )}
            ref={previewPaneRef}
          >
            <MarkdownPreviewHost
              assetResolver={assetResolver}
              extensions={extensions}
              fileAdapter={fileAdapter}
              frontmatterConfig={frontmatterConfig}
              frontmatterOpen={frontmatterOpen}
              headingIds={headingIds || outline}
              headingIdPrefix={headingIdPrefix}
              htmlPolicy={htmlPolicy}
              emoji={emoji}
              outline={outline}
              outlineVariant={outlineVariant}
              linkResolver={linkResolver}
              onChange={handlePreviewChange}
              onFrontmatterChange={onFrontmatterChange}
              sourcePath={sourcePath}
              value={value}
            />
          </section>
        ) : null}
      </div>
    </div>
  );
});

MiraMde.displayName = "MiraMde";

function syncSplitScroll(
  editorScroller: HTMLElement,
  previewPane: HTMLElement,
): () => void {
  const previewScroller =
    previewPane.querySelector<HTMLElement>(".mira-markdown-preview") ??
    previewPane;
  let activeSource: HTMLElement | null = null;
  let releaseFrame = 0;

  const sync = (source: HTMLElement, target: HTMLElement) => {
    if (activeSource && activeSource !== source) {
      return;
    }

    const sourceMax = source.scrollHeight - source.clientHeight;
    const targetMax = target.scrollHeight - target.clientHeight;
    if (sourceMax <= 0 || targetMax <= 0) {
      return;
    }

    activeSource = source;
    target.scrollTop = (source.scrollTop / sourceMax) * targetMax;
    cancelAnimationFrame(releaseFrame);
    releaseFrame = requestAnimationFrame(() => {
      activeSource = null;
    });
  };

  const syncPreview = () => sync(editorScroller, previewScroller);
  const syncEditor = () => sync(previewScroller, editorScroller);

  editorScroller.addEventListener("scroll", syncPreview, { passive: true });
  previewScroller.addEventListener("scroll", syncEditor, { passive: true });

  return () => {
    cancelAnimationFrame(releaseFrame);
    editorScroller.removeEventListener("scroll", syncPreview);
    previewScroller.removeEventListener("scroll", syncEditor);
  };
}

function themeClassName(theme: MiraTheme): string {
  if (theme === "dark") {
    return "mira-theme-dark theme-dark dark";
  }
  if (theme === "light") {
    return "mira-theme-light theme-light";
  }
  if (theme === "system") {
    return "mira-theme-system";
  }
  return "mira-theme-obsidian theme-light";
}

function useInheritedTheme(
  theme: MiraTheme,
  config: MiraThemeConfig | undefined,
  rootRef: RefObject<HTMLElement | null>,
): Exclude<MiraTheme, "inherit"> {
  const [inheritedTheme, setInheritedTheme] = useState<
    Exclude<MiraTheme, "inherit">
  >(config?.fallback ?? "system");

  useEffect(() => {
    if (theme !== "inherit" || typeof document === "undefined") {
      return;
    }

    const updateTheme = () => {
      setInheritedTheme(resolveInheritedTheme(rootRef.current, config));
    };
    updateTheme();

    const observer = new MutationObserver(updateTheme);
    for (const element of themeLookupTargets(rootRef.current, config)) {
      observer.observe(element, {
        attributeFilter: [
          "class",
          ...(config?.attributeNames ?? [
            "data-theme",
            "data-color-scheme",
            "data-mode",
          ]),
        ],
        attributes: true,
      });
    }

    return () => observer.disconnect();
  }, [config, rootRef, theme]);

  return inheritedTheme;
}

function resolveInheritedTheme(
  element: HTMLElement | null,
  config: MiraThemeConfig | undefined,
): Exclude<MiraTheme, "inherit"> {
  const darkClasses = config?.darkClassNames ?? [
    "dark",
    "theme-dark",
    "mira-theme-dark",
  ];
  const lightClasses = config?.lightClassNames ?? [
    "light",
    "theme-light",
    "mira-theme-light",
  ];
  const darkValues = config?.darkDataThemeValues ?? ["dark", "theme-dark"];
  const lightValues = config?.lightDataThemeValues ?? ["light", "theme-light"];
  const attributeNames = config?.attributeNames ?? [
    "data-theme",
    "data-color-scheme",
    "data-mode",
  ];

  for (const target of themeLookupTargets(element, config)) {
    for (const className of darkClasses) {
      if (target.classList.contains(className)) {
        return "dark";
      }
    }
    for (const className of lightClasses) {
      if (target.classList.contains(className)) {
        return "light";
      }
    }
    for (const attribute of attributeNames) {
      const value = target.getAttribute(attribute)?.toLowerCase();
      if (value && darkValues.includes(value)) {
        return "dark";
      }
      if (value && lightValues.includes(value)) {
        return "light";
      }
    }
  }

  return config?.fallback ?? "system";
}

function themeLookupTargets(
  element: HTMLElement | null,
  config: MiraThemeConfig | undefined,
): HTMLElement[] {
  if (typeof document === "undefined") {
    return [];
  }

  const configuredRoot = config?.root;
  const rootElement = isDocument(configuredRoot)
    ? configuredRoot.documentElement
    : configuredRoot;
  const targets: HTMLElement[] = [];
  let current: HTMLElement | null =
    rootElement ?? element?.parentElement ?? document.documentElement;

  while (current) {
    targets.push(current);
    current = current.parentElement;
  }

  if (document.body && !targets.includes(document.body)) {
    targets.push(document.body);
  }
  if (!targets.includes(document.documentElement)) {
    targets.push(document.documentElement);
  }

  return targets;
}

function isDocument(value: unknown): value is Document {
  return typeof Document !== "undefined" && value instanceof Document;
}

// packages/svelte/src/mira-mde.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Extension } from "@codemirror/state";
  import {
    createBaseCodeMirrorExtensions,
    createSlashCommandExtensions,
  } from "@mira-mde/codemirror";
  import { createMarkdownCodeMirrorExtensions } from "@mira-mde/codemirror-markdown";
  import { createRichEditorExtensions } from "@mira-mde/codemirror-rich";
  import { createTableExtensions } from "@mira-mde/codemirror-tables";
  import {
    createImageDropPasteExtension,
    createMiraEditorController,
    openImageFilePicker,
    type MiraEditorController,
  } from "@mira-mde/core";
  import {
    createMiraCommandKeymap,
    executeMiraCommand,
    isMiraCommandEnabled,
    mountMiraExtensionStyles,
    resolveMiraExtensions,
    type MiraCommand,
    type MiraExtensionRuntimeContext,
    type MiraMode,
    type MiraTemplateSelection,
  } from "@mira-mde/extensions";
  import { MarkdownOutline, MarkdownPreview } from "@mira-mde/preview";
  import { Button } from "@mira-mde/ui/button";
  import { Separator } from "@mira-mde/ui/separator";
  import * as ToggleGroup from "@mira-mde/ui/toggle-group";
  import type { MiraMdeProps } from "./types";

  let {
    value = $bindable(""),
    mode = $bindable("live-preview"),
    extensions = [],
    readonly = false,
    placeholder = "Start writing Markdown...",
    lineWrapping = true,
    spellcheck = true,
    blockControls = false,
    indentGuides = true,
    indentWithTabs = true,
    indentWidth = 4,
    theme = "obsidian",
    themeConfig,
    sourcePath,
    class: className = "",
    toolbar = true,
    linkResolver,
    assetResolver,
    fileAdapter,
    imageConfig,
    frontmatterOpen = true,
    frontmatterConfig,
    headingIds = false,
    headingIdPrefix = "",
    htmlPolicy = "trusted",
    emoji = false,
    outline = false,
    onChange,
    onFrontmatterChange,
  }: MiraMdeProps = $props();

  let editorHost: HTMLDivElement | null = $state(null);
  let previewPane: HTMLElement | null = $state(null);
  let rootEl: HTMLDivElement | null = $state(null);
  let controller: MiraEditorController | null = $state(null);
  let cleanupExtensionMounts: Array<() => void> = [];
  let inheritedTheme = $state<"obsidian" | "system" | "light" | "dark">(
    "system",
  );

  const resolvedExtensions = $derived(
    resolveMiraExtensions(extensions, {
      mode,
      readonly,
      sourcePath,
    }),
  );
  const extensionSignature = $derived(
    [
      mode,
      readonly,
      placeholder,
      lineWrapping,
      spellcheck,
      blockControls,
      indentGuides,
      indentWithTabs,
      indentWidth,
      sourcePath,
      JSON.stringify({
        max: imageConfig?.imageMaxSizeBytes,
        mime: imageConfig?.imageMimeTypes,
        syntax: imageConfig?.imageSyntax,
      }),
      extensions.map((extension) => extension.name).join(","),
      resolvedExtensions.slashCommands
        .map((command) =>
          [
            command.id,
            command.label,
            typeof command.insert === "string"
              ? command.insert
              : (command.insert?.markdown ?? ""),
            command.run ? "run" : "insert",
          ].join(":"),
        )
        .join(","),
    ].join("|"),
  );
  const showEditor = $derived(mode !== "preview");
  const showPreview = $derived(mode === "preview" || mode === "split");
  const themeClass = $derived(
    themeClassName(theme === "inherit" ? inheritedTheme : theme),
  );

  function buildCodeMirrorExtensions(): Extension[] {
    const resolved = resolveMiraExtensions(extensions, {
      mode,
      readonly,
      sourcePath,
    });

    return [
      createBaseCodeMirrorExtensions({
        readonly,
        placeholder,
        lineWrapping,
        spellcheck,
        indentWithTabs,
        indentWidth,
      }),
      createSlashCommandExtensions({
        commands: resolved.slashCommands,
      }),
      createMiraCommandKeymap(resolved.commands, (view) =>
        createExtensionRuntimeContext(controller, view),
      ),
      createMarkdownCodeMirrorExtensions({
        codeLanguages: resolved.codeLanguages,
        sourceMode: mode === "source",
      }),
      createTableExtensions(),
      createImageDropPasteExtension(imageConfig),
      createRichEditorExtensions({
        blockActions: resolved.blockActions,
        blockControls: blockControls && mode !== "preview" && !readonly,
        livePreview: mode === "live-preview",
        indentGuides,
        extensions,
        sourcePath,
        linkResolver,
        assetResolver,
        fileAdapter,
        frontmatterOpen,
        frontmatterConfig,
        onChange(replacement, from, to, nextValue) {
          if (controller) {
            controller.view.dispatch({
              changes: { from, to, insert: replacement },
            });
          } else {
            value = nextValue;
            onChange?.(nextValue);
          }
        },
        onFrontmatterChange,
      } as Parameters<typeof createRichEditorExtensions>[0] & {
        frontmatterConfig?: unknown;
        fileAdapter?: unknown;
      }),
      resolved.codeMirror,
    ].flat();
  }

  function runExtensionMounts(activeController: MiraEditorController): void {
    cleanupExtensionMounts.forEach((cleanup) => cleanup());
    cleanupExtensionMounts = [];

    for (const mountExtension of resolvedExtensions.onMount) {
      const cleanup = mountExtension(
        createExtensionRuntimeContext(activeController, activeController.view),
      );
      if (typeof cleanup === "function") {
        cleanupExtensionMounts.push(cleanup);
      }
    }
  }

  export function focus(): void {
    controller?.focus();
  }

  export function getMarkdown(): string {
    return controller?.getValue() ?? value;
  }

  export function setMarkdown(markdown: string): void {
    value = markdown;
    controller?.setValue(markdown);
  }

  export function getMode(): MiraMode {
    return mode;
  }

  export function getCommands(): readonly MiraCommand[] {
    return resolvedExtensions.commands;
  }

  export function isCommandEnabled(commandId: string): boolean {
    const command = findCommand(commandId);
    return Boolean(
      command &&
      isMiraCommandEnabled(command, createExtensionRuntimeContext(controller)),
    );
  }

  export function executeCommand(commandId: string): boolean {
    return executeMiraCommand(
      resolvedExtensions.commands,
      commandId,
      createExtensionRuntimeContext(controller),
    );
  }

  export function setMode(nextMode: MiraMode): void {
    mode = nextMode;
  }

  export function setReadonly(nextReadonly: boolean): void {
    readonly = nextReadonly;
  }

  export function getSelection(): ReturnType<
    MiraEditorController["getSelection"]
  > | null {
    return controller?.getSelection() ?? null;
  }

  export function setSelection(
    selection: ReturnType<MiraEditorController["getSelection"]>,
  ): void {
    controller?.setSelection(selection);
  }

  export function insertMarkdown(
    markdown: string,
    selection?: MiraTemplateSelection,
  ): void {
    controller?.replaceSelection(markdown, selection);
    controller?.focus();
  }

  export function insertImage(): void {
    if (controller) {
      openImageFilePicker(controller.view, imageConfig);
    }
  }

  onMount(() => {
    if (!editorHost) {
      return;
    }

    const activeController = createMiraEditorController({
      value,
      codeMirrorExtensions: buildCodeMirrorExtensions(),
      onChange(next) {
        value = next;
        onChange?.(next);
      },
    });

    activeController.mount(editorHost);
    controller = activeController;
    runExtensionMounts(activeController);

    return () => {
      cleanupExtensionMounts.forEach((cleanup) => cleanup());
      cleanupExtensionMounts = [];
      activeController.destroy();
      controller = null;
    };
  });

  $effect(() => {
    if (controller && value !== controller.getValue()) {
      controller.setValue(value);
    }
  });

  $effect(() => {
    return mountMiraExtensionStyles(resolvedExtensions.styles);
  });

  $effect(() => {
    resolvedExtensions;
    extensionSignature;
    if (controller) {
      controller.update({
        codeMirrorExtensions: buildCodeMirrorExtensions(),
      });
      runExtensionMounts(controller);
    }
  });

  $effect(() => {
    if (theme !== "inherit") {
      return;
    }

    inheritedTheme = resolveInheritedTheme(rootEl, themeConfig);
    const observer = new MutationObserver(() => {
      inheritedTheme = resolveInheritedTheme(rootEl, themeConfig);
    });

    for (const element of themeObservationTargets(rootEl, themeConfig)) {
      observer.observe(element, {
        attributeFilter: [
          "class",
          ...(themeConfig?.attributeNames ?? [
            "data-theme",
            "data-color-scheme",
            "data-mode",
          ]),
        ],
        attributes: true,
      });
    }

    return () => observer.disconnect();
  });

  $effect(() => {
    if (mode !== "split" || !controller || !previewPane) {
      return;
    }

    return syncSplitScroll(controller.view.scrollDOM, previewPane);
  });

  function themeClassName(
    value: "obsidian" | "system" | "light" | "dark" | "inherit",
  ): string {
    if (value === "dark") {
      return "mira-theme-dark theme-dark dark";
    }
    if (value === "light") {
      return "mira-theme-light theme-light";
    }
    if (value === "system") {
      return "mira-theme-system";
    }
    return "mira-theme-obsidian theme-light";
  }

  function resolveInheritedTheme(
    element: HTMLElement | null,
    config: typeof themeConfig,
  ): "obsidian" | "system" | "light" | "dark" {
    const darkClasses = config?.darkClassNames ?? [
      "dark",
      "theme-dark",
      "mira-theme-dark",
    ];
    const lightClasses = config?.lightClassNames ?? [
      "light",
      "theme-light",
      "mira-theme-light",
    ];
    const darkValues = config?.darkDataThemeValues ?? ["dark", "theme-dark"];
    const lightValues = config?.lightDataThemeValues ?? [
      "light",
      "theme-light",
    ];
    const attributeNames = config?.attributeNames ?? [
      "data-theme",
      "data-color-scheme",
      "data-mode",
    ];

    for (const target of themeLookupTargets(element, config)) {
      for (const className of darkClasses) {
        if (target.classList.contains(className)) {
          return "dark";
        }
      }
      for (const className of lightClasses) {
        if (target.classList.contains(className)) {
          return "light";
        }
      }
      for (const attribute of attributeNames) {
        const value = target.getAttribute(attribute)?.toLowerCase();
        if (value && darkValues.includes(value)) {
          return "dark";
        }
        if (value && lightValues.includes(value)) {
          return "light";
        }
      }
    }

    return config?.fallback ?? "system";
  }

  function themeLookupTargets(
    element: HTMLElement | null,
    config: typeof themeConfig,
  ): HTMLElement[] {
    if (typeof document === "undefined") {
      return [];
    }

    const configuredRoot = config?.root;
    const rootElement = isDocument(configuredRoot)
      ? configuredRoot.documentElement
      : configuredRoot;
    const targets: HTMLElement[] = [];
    let current: HTMLElement | null =
      rootElement ?? element?.parentElement ?? document.documentElement;
    while (current) {
      targets.push(current);
      current = current.parentElement;
    }
    if (document.body && !targets.includes(document.body)) {
      targets.push(document.body);
    }
    if (!targets.includes(document.documentElement)) {
      targets.push(document.documentElement);
    }
    return targets;
  }

  function themeObservationTargets(
    element: HTMLElement | null,
    config: typeof themeConfig,
  ): HTMLElement[] {
    return themeLookupTargets(element, config);
  }

  function isDocument(value: unknown): value is Document {
    return typeof Document !== "undefined" && value instanceof Document;
  }

  function syncSplitScroll(
    editorScroller: HTMLElement,
    previewPaneElement: HTMLElement,
  ): () => void {
    const previewScroller =
      previewPaneElement.querySelector<HTMLElement>(".mira-markdown-preview") ??
      previewPaneElement;
    let activeSource: HTMLElement | null = null;
    let releaseFrame = 0;

    const sync = (source: HTMLElement, target: HTMLElement) => {
      if (activeSource && activeSource !== source) {
        return;
      }

      const sourceMax = source.scrollHeight - source.clientHeight;
      const targetMax = target.scrollHeight - target.clientHeight;
      if (sourceMax <= 0 || targetMax <= 0) {
        return;
      }

      activeSource = source;
      target.scrollTop = (source.scrollTop / sourceMax) * targetMax;
      cancelAnimationFrame(releaseFrame);
      releaseFrame = requestAnimationFrame(() => {
        activeSource = null;
      });
    };

    const syncPreview = () => sync(editorScroller, previewScroller);
    const syncEditor = () => sync(previewScroller, editorScroller);

    editorScroller.addEventListener("scroll", syncPreview, { passive: true });
    previewScroller.addEventListener("scroll", syncEditor, { passive: true });

    return () => {
      cancelAnimationFrame(releaseFrame);
      editorScroller.removeEventListener("scroll", syncPreview);
      previewScroller.removeEventListener("scroll", syncEditor);
    };
  }

  function createExtensionRuntimeContext(
    activeController: MiraEditorController | null,
    view: unknown = activeController?.view,
  ): MiraExtensionRuntimeContext {
    return {
      view,
      mode,
      readonly,
      sourcePath,
      getValue: () => activeController?.getValue() ?? value,
      setValue(nextValue) {
        value = nextValue;
        activeController?.setValue(nextValue);
      },
      focus: () => activeController?.focus(),
      insertMarkdown,
      insertImage,
    };
  }

  function findCommand(commandId: string): MiraCommand | undefined {
    for (
      let index = resolvedExtensions.commands.length - 1;
      index >= 0;
      index -= 1
    ) {
      const command = resolvedExtensions.commands[index];
      if (command?.id === commandId) {
        return command;
      }
    }
    return undefined;
  }
</script>

<div
  bind:this={rootEl}
  class={`mira-mde ${themeClass} ${className}`.trim()}
  data-mode={mode}
  data-readonly={readonly}
>
  {#if toolbar}
    <div class="mira-mde__toolbar" aria-label="Markdown editor toolbar">
      <ToggleGroup.Root
        bind:value={mode}
        aria-label="Editor mode"
        onValueChange={(next) => (mode = next as MiraMode)}
      >
        <ToggleGroup.Item value="source">Source</ToggleGroup.Item>
        <ToggleGroup.Item value="live-preview">Live</ToggleGroup.Item>
        <ToggleGroup.Item value="preview">Preview</ToggleGroup.Item>
        <ToggleGroup.Item value="split">Split</ToggleGroup.Item>
      </ToggleGroup.Root>

      <Separator orientation="vertical" class="mira-mde__toolbar-separator" />

      <div class="mira-mde__actions">
        <Button
          variant="ghost"
          size="sm"
          onclick={() => insertMarkdown("**strong**")}
        >
          B
        </Button>
        <Button
          variant="ghost"
          size="sm"
          onclick={() => insertMarkdown("_emphasis_")}
        >
          I
        </Button>
        <Button
          variant="ghost"
          size="sm"
          onclick={() => insertMarkdown("[label](https://example.com)")}
        >
          Link
        </Button>
        <Button variant="ghost" size="sm" onclick={() => insertImage()}>
          Image
        </Button>
        <Button
          variant="ghost"
          size="sm"
          onclick={() =>
            insertMarkdown("\n```mermaid\ngraph TD\n  A --> B\n```\n")}
        >
          Mermaid
        </Button>
      </div>
    </div>
  {/if}

  <div class="mira-mde__body">
    <section
      class={`mira-mde__pane mira-mde__pane--editor markdown-editor-surface ${
        mode === "source"
          ? "markdown-view__editor--source markdown-source-mode"
          : "markdown-view__editor--live-preview markdown-live-preview-mode"
      }`}
      data-visible={showEditor}
      aria-hidden={showEditor ? "false" : "true"}
    >
      <div bind:this={editorHost} class="mira-mde__editor-host"></div>
    </section>

    {#if showPreview}
      <section
        bind:this={previewPane}
        class="mira-mde__pane mira-mde__pane--preview"
      >
        <MarkdownPreview
          {...{ frontmatterConfig } as any}
          class="markdown-reading-view"
          {value}
          {sourcePath}
          {extensions}
          {linkResolver}
          {assetResolver}
          {fileAdapter}
          {frontmatterOpen}
          headingIds={headingIds || outline}
          {headingIdPrefix}
          {htmlPolicy}
          {emoji}
          onChange={(replacement, from, to) => {
            const nextValue = `${value.slice(0, from)}${replacement}${value.slice(to)}`;
            value = nextValue;
            onChange?.(nextValue);
          }}
          {onFrontmatterChange}
        />
        {#if outline}
          <MarkdownOutline {value} {headingIdPrefix} />
        {/if}
      </section>
    {/if}
  </div>
</div>
