// packages/default-ui/src/default-mde.svelte
<script lang="ts">
  import CheckIcon from "@lucide/svelte/icons/check";
  import CodeIcon from "@lucide/svelte/icons/code";
  import CommandIcon from "@lucide/svelte/icons/command";
  import ImageIcon from "@lucide/svelte/icons/image";
  import LinkIcon from "@lucide/svelte/icons/link";
  import PlayIcon from "@lucide/svelte/icons/play";
  import RotateCcwIcon from "@lucide/svelte/icons/rotate-ccw";
  import SaveIcon from "@lucide/svelte/icons/save";
  import SparklesIcon from "@lucide/svelte/icons/sparkles";
  import TableIcon from "@lucide/svelte/icons/table-2";
  import WandSparklesIcon from "@lucide/svelte/icons/wand-sparkles";
  import { MiraMde, type MiraMdeHandle } from "@mira-mde/svelte";
  import type { MiraEditorSelection } from "@mira-mde/core";
  import {
    resolveMiraExtensions,
    type MiraMode,
    type MiraTemplateSelection,
    type MiraToolbarIconName,
  } from "@mira-mde/extensions";
  import type { Component } from "svelte";
  import MiraDefaultToolbar from "./default-toolbar.svelte";
  import {
    createMiraDefaultExtensions,
    defaultMiraEditMode,
    MiraFeature,
    resolveMiraDefaultFeatures,
    resolveMiraDefaultEditMode,
    resolveMiraDefaultModes,
    type MiraDefaultToolbarActionContext,
    type MiraDefaultToolbarDefinition,
  } from "./features";
  import type { MiraDefaultMdeProps } from "./types";

  let {
    value = $bindable(""),
    defaultEditMode = defaultMiraEditMode,
    mode = $bindable(defaultEditMode),
    readonly = false,
    placeholder = "Start writing Markdown...",
    lineWrapping = true,
    spellcheck = true,
    indentGuides = true,
    indentWithTabs = true,
    indentWidth = 4,
    theme = "obsidian",
    themeConfig,
    sourcePath,
    class: className = "",
    editorClass = "",
    features = {},
    featureConfigs = {},
    toolbarActions = [],
    toolbars = [],
    extensions = [],
    linkResolver,
    assetResolver,
    fileAdapter,
    imageConfig,
    authoring,
    frontmatterOpen = true,
    frontmatterConfig,
    headingIds = false,
    headingIdPrefix = "",
    htmlPolicy = "trusted",
    emoji = false,
    outline = false,
    outlineVariant = "floating",
    onChange,
    onModeChange,
    onReadonlyChange,
    onIndentGuidesChange,
    onIndentWidthChange,
    onIndentWithTabsChange,
    onFrontmatterChange,
  }: MiraDefaultMdeProps = $props();

  let editor: MiraMdeHandle | null = $state(null);

  const resolvedFeatures = $derived(resolveMiraDefaultFeatures(features));
  const modeOptions = $derived(resolveMiraDefaultModes(features));
  const resolvedDefaultEditMode = $derived(
    resolveMiraDefaultEditMode(defaultEditMode, modeOptions),
  );
  const activeExtensions = $derived([
    ...createMiraDefaultExtensions({ features, featureConfigs }),
    ...extensions,
  ]);
  const resolvedExtensionContributions = $derived(
    resolveMiraExtensions(activeExtensions, {
      mode,
      readonly,
      sourcePath,
    }),
  );
  const extensionToolbars = $derived.by(createExtensionToolbars);
  const activeToolbars = $derived([...extensionToolbars, ...toolbars]);

  const toolbarVisible = $derived(resolvedFeatures[MiraFeature.Toolbar]);
  const toolbarContext = $derived(createToolbarActionContext());

  function handleChange(nextValue: string): void {
    value = nextValue;
    onChange?.(nextValue);
  }

  function applyMode(nextMode: MiraMode): void {
    if (!modeOptions.includes(nextMode)) {
      return;
    }
    mode = nextMode;
    onModeChange?.(nextMode);
  }

  function applyReadonly(nextReadonly: boolean): void {
    readonly = nextReadonly;
    onReadonlyChange?.(nextReadonly);
  }

  function applyIndentGuides(nextEnabled: boolean): void {
    indentGuides = nextEnabled;
    onIndentGuidesChange?.(nextEnabled);
  }

  function applyIndentWidth(nextWidth: number): void {
    indentWidth = nextWidth;
    onIndentWidthChange?.(nextWidth);
  }

  function applyIndentWithTabs(nextEnabled: boolean): void {
    indentWithTabs = nextEnabled;
    onIndentWithTabsChange?.(nextEnabled);
  }

  function createToolbarActionContext(): MiraDefaultToolbarActionContext {
    return {
      value,
      mode,
      readonly,
      focus,
      getIndentGuides: () => indentGuides,
      getIndentWidth: () => indentWidth,
      getIndentWithTabs: () => indentWithTabs,
      getMarkdown,
      getMode,
      getSelection,
      insertImage,
      insertMarkdown,
      setIndentGuides: applyIndentGuides,
      setIndentWidth: applyIndentWidth,
      setIndentWithTabs: applyIndentWithTabs,
      setMarkdown,
      setMode,
      setReadonly,
      setSelection,
    };
  }

  export function focus(): void {
    editor?.focus();
  }

  export function executeCommand(commandId: string): boolean {
    return editor?.executeCommand(commandId) ?? false;
  }

  export function getCommands(): ReturnType<MiraMdeHandle["getCommands"]> {
    return editor?.getCommands() ?? resolvedExtensionContributions.commands;
  }

  export function isCommandEnabled(commandId: string): boolean {
    return editor?.isCommandEnabled(commandId) ?? false;
  }

  export function getMarkdown(): string {
    return editor?.getMarkdown() ?? value;
  }

  export function setMarkdown(markdown: string): void {
    value = markdown;
    editor?.setMarkdown(markdown);
  }

  export function getMode(): MiraMode {
    return mode;
  }

  export function setMode(nextMode: MiraMode): void {
    if (!modeOptions.includes(nextMode)) {
      return;
    }
    applyMode(nextMode);
    editor?.setMode(nextMode);
  }

  export function setReadonly(nextReadonly: boolean): void {
    applyReadonly(nextReadonly);
    editor?.setReadonly(nextReadonly);
  }

  export function getSelection(): MiraEditorSelection | null {
    return editor?.getSelection() ?? null;
  }

  export function setSelection(selection: MiraEditorSelection): void {
    editor?.setSelection(selection);
  }

  export function insertMarkdown(
    markdown: string,
    selection?: MiraTemplateSelection,
  ): void {
    editor?.insertMarkdown(markdown, selection);
  }

  export function insertImage(): void {
    editor?.insertImage();
  }

  function createExtensionToolbars(): MiraDefaultToolbarDefinition[] {
    const groups = new Map<string, MiraDefaultToolbarDefinition>();

    for (const item of resolvedExtensionContributions.toolbarItems) {
      const align = item.align ?? "start";
      const label = item.group ?? "Extensions";
      const key = `${align}:${label}`;
      let group = groups.get(key);
      if (!group) {
        group = {
          id: `extension-${slugify(label)}-${align}`,
          label,
          align,
          items: [],
        };
        groups.set(key, group);
      }

      group.items.push({
        id: `extension-${item.id}`,
        label: item.label,
        tooltip: item.tooltip,
        icon: extensionToolbarIcon(item.icon),
        disabled: () => (editor ? !isCommandEnabled(item.command) : false),
        run: () => {
          executeCommand(item.command);
        },
      });
    }

    return [...groups.values()];
  }

  function extensionToolbarIcon(
    icon: MiraToolbarIconName | undefined,
  ): Component<Record<string, unknown>> {
    return extensionToolbarIcons[icon ?? "command"] ?? CommandIcon;
  }

  function slugify(value: string): string {
    return (
      value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "extensions"
    );
  }

  const extensionToolbarIcons: Record<
    MiraToolbarIconName,
    Component<Record<string, unknown>>
  > = {
    check: CheckIcon,
    code: CodeIcon,
    command: CommandIcon,
    image: ImageIcon,
    link: LinkIcon,
    play: PlayIcon,
    "rotate-ccw": RotateCcwIcon,
    save: SaveIcon,
    sparkles: SparklesIcon,
    table: TableIcon,
    "wand-sparkles": WandSparklesIcon,
  };

  $effect(() => {
    if (!modeOptions.includes(mode) && modeOptions[0]) {
      applyMode(modeOptions[0]);
    }
  });
</script>

<div
  class={`mira-default-ui ${className}`.trim()}
  data-mode={mode}
  data-readonly={readonly}
>
  {#if toolbarVisible}
    <MiraDefaultToolbar
      bind:mode
      {value}
      {readonly}
      {features}
      {featureConfigs}
      defaultEditMode={resolvedDefaultEditMode}
      {toolbarActions}
      toolbars={activeToolbars}
      context={toolbarContext}
      {indentGuides}
      {indentWidth}
      {indentWithTabs}
      onIndentGuidesChange={applyIndentGuides}
      onIndentWidthChange={applyIndentWidth}
      onIndentWithTabsChange={applyIndentWithTabs}
    />
  {/if}

  <div class="mira-default-ui__editor">
    <MiraMde
      {...{ frontmatterConfig } as any}
      bind:this={editor}
      bind:value
      bind:mode
      class={editorClass}
      {readonly}
      {placeholder}
      {lineWrapping}
      {spellcheck}
      {indentGuides}
      {indentWithTabs}
      {indentWidth}
      {theme}
      {themeConfig}
      {sourcePath}
      blockControls={resolvedFeatures[MiraFeature.BlockControls] &&
        featureConfigs[MiraFeature.BlockControls]?.enabled !== false}
      toolbar={false}
      extensions={activeExtensions}
      {linkResolver}
      {assetResolver}
      {fileAdapter}
      {imageConfig}
      {authoring}
      frontmatterOpen={resolvedFeatures[MiraFeature.Frontmatter] &&
        frontmatterOpen}
      {headingIds}
      {headingIdPrefix}
      {htmlPolicy}
      {emoji}
      {outline}
      {outlineVariant}
      onChange={handleChange}
      {onFrontmatterChange}
    />
  </div>
</div>

// packages/react/src/default-mde.tsx
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  Check,
  Code,
  Command,
  Image,
  Link,
  Play,
  RotateCcw,
  Save,
  Sparkles,
  Table2,
  WandSparkles,
} from "lucide-react";
import type { MiraEditorSelection } from "@mira-mde/core";
import {
  resolveMiraExtensions,
  type MiraMode,
  type MiraToolbarIconName,
} from "@mira-mde/extensions";
import { MiraDefaultToolbar } from "./default-toolbar";
import {
  createMiraDefaultExtensions,
  defaultMiraEditMode,
  MiraFeature,
  resolveMiraDefaultFeatures,
  resolveMiraDefaultEditMode,
  resolveMiraDefaultModes,
} from "./features";
import { cx } from "./hooks";
import { MiraMde } from "./mira-mde";
import type {
  MiraDefaultMdeHandle,
  MiraDefaultMdeProps,
  MiraDefaultToolbarActionContext,
  MiraDefaultToolbarDefinition,
  MiraMdeHandle,
  MiraReactIcon,
} from "./types";

const extensionToolbarIcons: Record<MiraToolbarIconName, MiraReactIcon> = {
  check: Check,
  code: Code,
  command: Command,
  image: Image,
  link: Link,
  play: Play,
  "rotate-ccw": RotateCcw,
  save: Save,
  sparkles: Sparkles,
  table: Table2,
  "wand-sparkles": WandSparkles,
};

export const MiraDefaultMde = forwardRef<
  MiraDefaultMdeHandle,
  MiraDefaultMdeProps
>(function MiraDefaultMde(
  {
    assetResolver,
    authoring,
    className,
    defaultEditMode = defaultMiraEditMode,
    defaultMode = defaultEditMode,
    defaultReadonly = false,
    defaultValue = "",
    editorClassName,
    extensions = [],
    fileAdapter,
    imageConfig,
    featureConfigs = {},
    features = {},
    frontmatterConfig,
    frontmatterOpen = true,
    headingIds = false,
    headingIdPrefix = "",
    htmlPolicy = "trusted",
    emoji = false,
    outline = false,
    outlineVariant = "floating",
    indentGuides: indentGuidesProp,
    indentWithTabs: indentWithTabsProp,
    indentWidth: indentWidthProp,
    lineWrapping = true,
    linkResolver,
    mode: modeProp,
    onChange,
    onFrontmatterChange,
    onIndentGuidesChange,
    onIndentWidthChange,
    onIndentWithTabsChange,
    onModeChange,
    onReadonlyChange,
    placeholder = "Start writing Markdown...",
    readonly: readonlyProp,
    sourcePath,
    spellcheck = true,
    theme = "obsidian",
    themeConfig,
    toolbarActions = [],
    toolbars = [],
    value: valueProp,
  },
  ref,
) {
  const editorRef = useRef<MiraMdeHandle | null>(null);
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
  const [uncontrolledMode, setUncontrolledMode] = useState(defaultMode);
  const [uncontrolledReadonly, setUncontrolledReadonly] =
    useState(defaultReadonly);
  const [uncontrolledIndentGuides, setUncontrolledIndentGuides] =
    useState(true);
  const [uncontrolledIndentWithTabs, setUncontrolledIndentWithTabs] =
    useState(true);
  const [uncontrolledIndentWidth, setUncontrolledIndentWidth] = useState(4);
  const value = valueProp ?? uncontrolledValue;
  const mode = modeProp ?? uncontrolledMode;
  const readonly = readonlyProp ?? uncontrolledReadonly;
  const indentGuides = indentGuidesProp ?? uncontrolledIndentGuides;
  const indentWithTabs = indentWithTabsProp ?? uncontrolledIndentWithTabs;
  const indentWidth = indentWidthProp ?? uncontrolledIndentWidth;
  const resolvedFeatures = useMemo(
    () => resolveMiraDefaultFeatures(features),
    [features],
  );
  const modeOptions = useMemo(
    () => resolveMiraDefaultModes(features),
    [features],
  );
  const resolvedDefaultEditMode = useMemo(
    () => resolveMiraDefaultEditMode(defaultEditMode, modeOptions),
    [defaultEditMode, modeOptions],
  );
  const activeExtensions = useMemo(
    () => [
      ...createMiraDefaultExtensions({ featureConfigs, features }),
      ...extensions,
    ],
    [extensions, featureConfigs, features],
  );
  const resolvedExtensionContributions = useMemo(
    () =>
      resolveMiraExtensions(activeExtensions, {
        mode,
        readonly,
        sourcePath,
      }),
    [activeExtensions, mode, readonly, sourcePath],
  );
  const extensionToolbars = useMemo(() => {
    const groups = new Map<string, MiraDefaultToolbarDefinition>();

    for (const item of resolvedExtensionContributions.toolbarItems) {
      const align = item.align ?? "start";
      const label = item.group ?? "Extensions";
      const key = `${align}:${label}`;
      let group = groups.get(key);
      if (!group) {
        group = {
          id: `extension-${slugify(label)}-${align}`,
          label,
          align,
          items: [],
        };
        groups.set(key, group);
      }

      const Icon = extensionToolbarIcons[item.icon ?? "command"] ?? Command;
      group.items.push({
        id: `extension-${item.id}`,
        label: item.label,
        tooltip: item.tooltip,
        icon: Icon,
        disabled: () =>
          editorRef.current
            ? !editorRef.current.isCommandEnabled(item.command)
            : false,
        run: () => {
          editorRef.current?.executeCommand(item.command);
        },
      });
    }

    return [...groups.values()];
  }, [resolvedExtensionContributions.toolbarItems]);

  const handleChange = useCallback(
    (nextValue: string) => {
      if (valueProp === undefined) {
        setUncontrolledValue(nextValue);
      }
      onChange?.(nextValue);
    },
    [onChange, valueProp],
  );

  const applyMode = useCallback(
    (nextMode: MiraMode) => {
      if (!modeOptions.includes(nextMode)) {
        return;
      }
      if (modeProp === undefined) {
        setUncontrolledMode(nextMode);
      }
      onModeChange?.(nextMode);
    },
    [modeOptions, modeProp, onModeChange],
  );

  const applyReadonly = useCallback(
    (nextReadonly: boolean) => {
      if (readonlyProp === undefined) {
        setUncontrolledReadonly(nextReadonly);
      }
      onReadonlyChange?.(nextReadonly);
    },
    [onReadonlyChange, readonlyProp],
  );

  const applyIndentGuides = useCallback(
    (nextEnabled: boolean) => {
      if (indentGuidesProp === undefined) {
        setUncontrolledIndentGuides(nextEnabled);
      }
      onIndentGuidesChange?.(nextEnabled);
    },
    [indentGuidesProp, onIndentGuidesChange],
  );

  const applyIndentWithTabs = useCallback(
    (nextEnabled: boolean) => {
      if (indentWithTabsProp === undefined) {
        setUncontrolledIndentWithTabs(nextEnabled);
      }
      onIndentWithTabsChange?.(nextEnabled);
    },
    [indentWithTabsProp, onIndentWithTabsChange],
  );

  const applyIndentWidth = useCallback(
    (nextWidth: number) => {
      if (indentWidthProp === undefined) {
        setUncontrolledIndentWidth(nextWidth);
      }
      onIndentWidthChange?.(nextWidth);
    },
    [indentWidthProp, onIndentWidthChange],
  );

  const handleSetMarkdown = useCallback(
    (markdown: string) => {
      if (valueProp === undefined) {
        setUncontrolledValue(markdown);
      }
      editorRef.current?.setMarkdown(markdown);
    },
    [valueProp],
  );

  const handleSetMode = useCallback(
    (nextMode: MiraMode) => {
      applyMode(nextMode);
      editorRef.current?.setMode(nextMode);
    },
    [applyMode],
  );

  const handleSetReadonly = useCallback(
    (nextReadonly: boolean) => {
      applyReadonly(nextReadonly);
      editorRef.current?.setReadonly(nextReadonly);
    },
    [applyReadonly],
  );

  const toolbarContext = useMemo<MiraDefaultToolbarActionContext>(
    () => ({
      focus: () => editorRef.current?.focus(),
      getIndentGuides: () => indentGuides,
      getIndentWidth: () => indentWidth,
      getIndentWithTabs: () => indentWithTabs,
      getMarkdown: () => editorRef.current?.getMarkdown() ?? value,
      getMode: () => editorRef.current?.getMode() ?? mode,
      getSelection: () => editorRef.current?.getSelection() ?? null,
      insertImage: () => editorRef.current?.insertImage(),
      insertMarkdown: (markdown) => editorRef.current?.insertMarkdown(markdown),
      mode,
      readonly,
      setIndentGuides: applyIndentGuides,
      setIndentWidth: applyIndentWidth,
      setIndentWithTabs: applyIndentWithTabs,
      setMarkdown: handleSetMarkdown,
      setMode: handleSetMode,
      setReadonly: handleSetReadonly,
      setSelection: (selection) => editorRef.current?.setSelection(selection),
      value,
    }),
    [
      handleSetMarkdown,
      handleSetMode,
      handleSetReadonly,
      applyIndentGuides,
      applyIndentWidth,
      applyIndentWithTabs,
      indentGuides,
      indentWidth,
      indentWithTabs,
      mode,
      readonly,
      value,
    ],
  );

  useImperativeHandle(
    ref,
    () => ({
      executeCommand(commandId) {
        return editorRef.current?.executeCommand(commandId) ?? false;
      },
      focus() {
        editorRef.current?.focus();
      },
      getMarkdown() {
        return editorRef.current?.getMarkdown() ?? value;
      },
      getCommands() {
        return (
          editorRef.current?.getCommands() ??
          resolvedExtensionContributions.commands
        );
      },
      getMode() {
        return editorRef.current?.getMode() ?? mode;
      },
      getSelection() {
        return editorRef.current?.getSelection() ?? null;
      },
      insertMarkdown(markdown) {
        editorRef.current?.insertMarkdown(markdown);
      },
      insertImage() {
        editorRef.current?.insertImage();
      },
      isCommandEnabled(commandId) {
        return editorRef.current?.isCommandEnabled(commandId) ?? false;
      },
      setMarkdown: handleSetMarkdown,
      setMode: handleSetMode,
      setReadonly: handleSetReadonly,
      setSelection(selection: MiraEditorSelection) {
        editorRef.current?.setSelection(selection);
      },
    }),
    [
      handleSetMarkdown,
      handleSetMode,
      handleSetReadonly,
      mode,
      resolvedExtensionContributions.commands,
      value,
    ],
  );

  return (
    <div
      className={cx("mira-default-ui", className)}
      data-mode={mode}
      data-readonly={readonly}
    >
      {resolvedFeatures[MiraFeature.Toolbar] ? (
        <MiraDefaultToolbar
          context={toolbarContext}
          defaultEditMode={resolvedDefaultEditMode}
          featureConfigs={featureConfigs}
          features={features}
          indentGuides={indentGuides}
          indentWidth={indentWidth}
          indentWithTabs={indentWithTabs}
          mode={mode}
          modeOptions={modeOptions}
          onIndentGuidesChange={applyIndentGuides}
          onIndentWidthChange={applyIndentWidth}
          onIndentWithTabsChange={applyIndentWithTabs}
          readonly={readonly}
          toolbarActions={toolbarActions}
          toolbars={[...extensionToolbars, ...toolbars]}
          value={value}
        />
      ) : null}

      <div className="mira-default-ui__editor">
        <MiraMde
          assetResolver={assetResolver}
          authoring={authoring}
          blockControls={
            resolvedFeatures[MiraFeature.BlockControls] &&
            featureConfigs[MiraFeature.BlockControls]?.enabled !== false
          }
          className={editorClassName}
          defaultMode={defaultMode}
          defaultReadonly={defaultReadonly}
          defaultValue={defaultValue}
          extensions={activeExtensions}
          fileAdapter={fileAdapter}
          imageConfig={imageConfig}
          frontmatterConfig={frontmatterConfig}
          frontmatterOpen={
            resolvedFeatures[MiraFeature.Frontmatter] && frontmatterOpen
          }
          headingIds={headingIds}
          headingIdPrefix={headingIdPrefix}
          htmlPolicy={htmlPolicy}
          emoji={emoji}
          outline={outline}
          outlineVariant={outlineVariant}
          indentGuides={indentGuides}
          indentWidth={indentWidth}
          indentWithTabs={indentWithTabs}
          lineWrapping={lineWrapping}
          linkResolver={linkResolver}
          mode={mode}
          onChange={handleChange}
          onFrontmatterChange={onFrontmatterChange}
          onModeChange={applyMode}
          onReadonlyChange={applyReadonly}
          placeholder={placeholder}
          readonly={readonly}
          ref={editorRef}
          sourcePath={sourcePath}
          spellcheck={spellcheck}
          theme={theme}
          themeConfig={themeConfig}
          toolbar={false}
          value={value}
        />
      </div>
    </div>
  );
});

MiraDefaultMde.displayName = "MiraDefaultMde";

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") || "extensions"
  );
}
